name: 🧪 Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: 🧹 lint
    uses: ./.github/workflows/reusable-lint.yml

  test:
    name: 🧪 test
    uses: ./.github/workflows/reusable-test.yml
    needs: lint
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: 📦 build
    uses: ./.github/workflows/reusable-build.yml
    needs: lint
